spring:
  profiles:
    active: local
  config:
    import:
      - db-core.yml
      - oauth.yml
      - logging.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - swagger.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - swagger.yml
---
spring:
  config:
    activate:
      on-profile: prod
