spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

datasource:
  db:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true
---
spring:
  config:
    activate:
      on-profile: prod

datasource:
  db:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${datasource.db-core.url}
      username: ${datasource.db-core.username}
      password: ${datasource.db-core.password}
      pool-name: core-db-pool
      maximum-pool-size: 10
      connection-timeout: 1000
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      data-source-properties:
        rewriteBatchedStatements: true
